### ISSUE TITLE
很不错的项目，

### ISSUE THREAD

**Issue by mengxiangke** [HuJK/O365-UC#1]
不过教程看得我头皮发麻，有时间试试。

**Comment by mengxiangke** [comment]
安装完成，测试一下很不错，但是吗，没有python web的开发经验，有点难以扩展功能。比如限制别人恶意注册。希望大佬进一步开发。

**Comment by lanhui672** [comment]
> 安装完成，测试一下很不错，但是吗，没有python web的开发经验，有点难以扩展功能。某些限制别人恶意注册。希望大佬进一步开发。

大佬，我执行这一步出错了，你知道什么原因吗
tmux new -d -s o365 python3 o365-creater_api.py
报错-bash: tmux: command not found
已经安装了tmux /tornado/python3和2共存的

**Comment by mengxiangke** [comment]
> > 安装完成，测试一下很不错，但是吗，没有python web的开发经验，有点难以扩展功能。某些限制别人恶意注册。希望大佬进一步开发。
> 
> 大佬，我执行这一步出错了，你知道什么原因吗
> tmux new -d -s o365 python3 o365-creater_api.py
> 报错-bash: tmux: command not found
> 已经安装了tmux /tornado/python3和2共存的

最好使用ubuntu 18，可以尝试安装tmux

**Comment by lanhui672** [comment]
> > > 安装完成，测试一下很不错，但是吗，没有python web的开发经验，有点难以扩展功能。某些限制别人恶意注册。希望大佬进一步开发。
> > 
> > 
> > 大佬，我执行这一步出错了，你知道什么原因吗
> > TMUX新-d -s O365 python3 o365-creater_api.py 
> > 报错-bash：TMUX：命令没有发现
> > 已经安装了TMUX /龙卷风/ python3和2共存的
> 
> 最好使用ubuntu 18，可以尝试安装tmux

好的，可能是centos的问题（谢谢）

**Comment by HuJK** [comment]
新增了reCAPTCHA/hCAPTCHA的支援。

其實python只是api server而已，前端是vue+vuetify。

前後端是完全分離的

**Comment by HuJK** [comment]
教程問題...我不太會寫，不知道怎麼寫得容易懂耶...

今天稍作了一些修改，不知道有沒有比較好懂?
