### ISSUE TITLE
能取消强制的https访问嘛

### ISSUE THREAD

**Issue by hechuan4** [HuJK/O365-UC#2]
能取消强制的https访问嘛

**Comment by HuJK** [comment]
不行耶...這個是微軟那邊的限制。
我之前debug很久，發現https://apps.dev.microsoft.com/?deepLink=/quickstart/graphIO 這個API如果沒給他https就不能運作。

其實理論上是可以的，我們用http訪問，但是給微軟API裡面傳https的地址。

這樣的話API不會出錯，但是安裝教學中的第15步有個自動取得token的過程，因為地址不匹配，導致微軟沒辦法把code傳回來。
這樣要手動去API管理中心自己取得token，十分麻煩。

我想了想還是強制https算了，省的我還要解釋怎麼去API管理中心自己取得token
